### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by rapha8l** [yyyyyyyan/bandcamper#1]
Hi,

I tried to make a setup.py but it seems I'm too noob for that, would mind making one ?
Thanks

**Comment by rapha8l** [comment]
Thanks !
Have a nice day

**Comment by yyyyyyyan** [comment]
hey, I'm having to delay the beta release to this next week. Sorry about that.

**Comment by rapha8l** [comment]
No problem !

**Comment by yyyyyyyan** [comment]
Hey @rapha8l! After almost a year I released an alpha version of bandcamper :D that works and is ready to be tested. It still needs lots of tweaks and refactoring, but it's working ;). If you're still interested in the tool, make sure to check it out!

**Comment by rapha8l** [comment]
Thanks, I'll have a look :)
Have a nice weekend

**Comment by yyyyyyyan** [comment]
You too!:smile:
