### ISSUE TITLE
Sanitize folder/file names for output.

### ISSUE THREAD

**Issue by colt45rpm** [yyyyyyyan/bandcamper#6]
Can you clean/sanitize the output folder and file names? Crashes occur when you try to write file or folder names that are not allowed on Linux/Windows.

Maybe use https://pypi.org/project/sanitize-filename/

**Comment by Iemand005** [comment]
I was having the same issue, fixed it myself for now by adding 
`file_path /= filename.format(ext=file_ext)`
`file_path = Path(str(file_path).replace("|",""))` <-- this line to the downoad path and the path the downloaded file is moved to.
`with file_path.open("wb") as file:`

You can simply add a .replace to the .replace for all the other not allowed characters. This is probably the easiest solution. I may do a pull request for this.
